services:
  db:
    image: postgres:alpine3.17
    env_file:
      - variables.env
    ports:
      - "5433:5432"
    restart: on-failure
    container_name: cont_psql_oaw_db
  backend:
    build:
      context: .
    depends_on:
      - db
    env_file:
      - variables.env
    ports:
      - "80:8080"
    container_name: cont_oaw_backend
