services:
  db:
    image: postgres:alpine3.17
    environment:
      - POSTGRES_DB=oaw_db
      - POSTGRES_USER=person
      - POSTGRES_PASSWORD=person
    ports:
      - "5433:5432"
    restart: on-failure
    container_name: cont_psql_oaw_db
  backend:
    build:
      context: .
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
    ports:
      - "80:8080"
    container_name: cont_oaw_backend
